### PR TITLE
added societal to registry

### PR DESCRIPTION
**Pull request by gfox1**

### CODE REVIEW

**Comment by gfox1** [comment]
Hi @DanielCake-Baly, I just wanted to check if you needed anything else from my end to merge this?

**Comment by DanielCake-Baly** [comment]
> Hi @DanielCake-Baly, I just wanted to check if you needed anything else from my end to merge this?

Hi, 
thanks for checking. 
Could you please contact me on [Element](https://matrix.to/#/@daniel.cake-baly:matrix.parity.io)?

**Comment by gfox1** [comment]
Hey @DanielCake-Baly, just sent you a message on Element.

**Review by DanielCake-Baly — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@gfox1 please merge master

**Comment by bkchr** [comment]
@gfox1 github still says that the branch has conflicts.

**Comment by gfox1** [comment]
@bkchr this should be good to merge now. Thanks!

**Pull request merged**
