### PR TITLE
add anmol mainnet and testnet address prefixes

### PR DESCRIPTION
**Pull request by justinFrevert**
The Anmol team wishes to register the 100 prefix for our testnet: ibtida & 92 prefix for our mainnet. This is to easily identify addresses and to prevent re-use across our imminently launching test net and future mainnet.

Please let us know of any feedback and thank you for your time.

### CODE REVIEW

**Comment by BenWhiteJam** [comment]
@justinFrevert just following up on this, do you have a public endpoint for the testnet? Is 100 a testnet or a canary network? Testnets don't need a prefix

**Comment by justinFrevert** [comment]
I believe @nblogist had taken over this at some point, so he may need to make a decision based on that information.

**Comment by nblogist** [comment]
Thank you @justinFrevert @BenWhiteJam, @vedhavyas will be working on this now.

**Comment by vedhavyas** [comment]
@BenWhiteJam 100 is canary network.

**Comment by DanielCake-Baly** [comment]
> Thank you @justinFrevert @BenWhiteJam, @vedhavyas will be working on this now.

@nblogist  I would like to get in contact, could you please reach out on [Element](https://matrix.to/#/@daniel.cake-baly:matrix.parity.io ) ? Thanks in advance!

**Comment by nblogist** [comment]
Hey @DanielCake-Baly I have recently lost access to my element. Can you please reach out on my telegram @furqanahmed18

**Comment by DanielCake-Baly** [comment]
> Hey @DanielCake-Baly I have recently lost access to my element. Can you please reach out on my telegram @furqanahmed18

Thx @nblogist , I just did.

**Review by BenWhiteJam — APPROVED** [review]

**Review by bkchr — APPROVED** [review]
Please merge master

**Comment by DanielCake-Baly** [comment]
Hey @nblogist, a kind reminder.

**Comment by nblogist** [comment]
Thank you @DanielCake-Baly will be doing it this week

**Pull request merged**
