### PR TITLE
Add Setheum

### PR DESCRIPTION
**Pull request by alfellati**
```
{
      "prefix": 204,
      "network": "setheum",
      "displayName": "Setheum",
      "symbols": ["SETM"],
      "decimals": [18],
      "standardAccount": "*25519",
      "website": "https://setheum.xyz"
    },
```

### CODE REVIEW

**Comment by JBA-Khalifa** [comment]
Hi, I'm just wondering, could it be that I get this error: https://github.com/setheum-js/console/issues/17 BECAUSE OUR prefix is not in this registry yet?

And I want to change it to 204 if so, thank you @BenWhiteJam

**Comment by DanielCake-Baly** [comment]
> Hi, I'm just wondering, could it be that I get this error: [setheum-js/console#17](https://github.com/setheum-js/console/issues/17) BECAUSE OUR prefix is not in this registry yet?
> 
> And I want to change it to 204 if so, thank you @BenWhiteJam

Hi @JBA-Khalifa , could you please get in contact with me on [Element](https://matrix.to/#/@daniel.cake-baly:matrix.parity.io) ? Thanks in advance!

**Comment by JBA-Khalifa** [comment]
Yes, thanks a lot. I will add you now.. am so sorry for the late reply

**Comment by DanielCake-Baly** [comment]
> 

Hey @JBA-Khalifa, hope you are well!
Any success setting up Element? If not, Telegram is good as well!

**Comment by DanielCake-Baly** [comment]
Hey @JBA-Khalifa, Could you please contact me on [Element](https://matrix.to/#/@daniel_cb:parity.io)? Thanks in advance!

**Comment by itsbirdo** [comment]
No reply and the project looks like it is unmaintained based on website / socials. Closing this for now.

**Pull request closed without merging**
