### PR TITLE
Rebrand HydraDX -> Hydration

### PR DESCRIPTION
**Pull request by jak-pan**
Rebranded HydraDX to Hydration and added hydration chain to keep the compatibility

### CODE REVIEW

**Comment by bkchr** [comment]
I don't think we support duplicate ids.

**Comment by jak-pan** [comment]
> I don't think we support duplicate ids.

Hm... Okay... Can we just kill this with fire?

**Comment by bkchr** [comment]
> Hm... Okay... Can we just kill this with fire?

Probably. Not sure if anyone (probably someone) is using this `network` field.

**Comment by jak-pan** [comment]
> > Hm... Okay... Can we just kill this with fire?
> 
> Probably. Not sure if anyone (probably someone) is using this `network` field.

It's mapped to the genesis hash by network field AFAIK

**Review by bkchr — APPROVED** [review]

**Pull request merged**
