### PR TITLE
Add Fragnova Network

### PR DESCRIPTION
**Pull request by sinkingsugar**
Hello, Giovanni from Fragnova/Fragcolor here. ( https://fragnova.com / https://fragcolor.com )
We are about to launch testnet this month and mainnet probably few months after.
Would love to get this merged.
Thanks 🙏

### CODE REVIEW

**Comment by bkchr** [comment]
Test nets don't need their own prefix.

**Comment by sinkingsugar** [comment]
Ah sorry I should have explained more. Our definition of testnet is fairly different.

It's actually called Beta and acts more like Kusama is for Polkadot.
Users will interact with them quite a lot before games go fully live on the main chain. And even after release they will be used as pre-release realm. That's why the user experience is paramount.

Thanks 🙏

**Comment by bkchr** [comment]
But why can the Beta chain not just use the generic prefix?

**Comment by sinkingsugar** [comment]
@bkchr You raise a very good point. Fixed it. Thanks 🙏

**Comment by mroseneo** [comment]
Hi guys, can we get any update on this?

**Review by BenWhiteJam — APPROVED** [review]

**Pull request merged**
