### PR TITLE
Update Darwinia Network

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@AurevoirXavier please merge master.

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier please merge master.

Done.

**Comment by bkchr** [comment]
@AurevoirXavier would it also be possible to fix the failing test? It was using your token :see_no_evil:

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier would it also be possible to fix the failing test? It was using your token 🙈

The purpose of this test case is to verify the functionality of multi-tokens. Currently, we are utilizing pallet-assets to handle the management of these tokens. Therefore, I have removed it.

**Pull request merged**
