### PR TITLE
Add westend

### PR DESCRIPTION
**Pull request by Nick-1979**
Westend testnet has been using in many developing environments, hence it would be handy to add it to the ss58-registry.

### CODE REVIEW

**Comment by bkchr** [comment]
Westend is a test net and test nets are using the generic prefix `42`.

**Comment by Nick-1979** [comment]
Yes, I see, thank you, Is there any way to add Westend to the ss58-registry?
I always add it manually to ss58-registry in my projects, hence if there is any way to add it officially helps a lot.

**Comment by bkchr** [comment]
Can you elaborate a little bit more why you need this?

**Comment by Nick-1979** [comment]
Hello Bastian,

ss58-registry is a dependency of Polkadot Js Plus,We are working on Polkadot js PLUS extension which is deploying on top of the original extension.
To provide the ability of testing & learning Polkadot ecosystem we have added Westend as a supported chain to the PLUS extension. it is already available here: https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-plus-extension/

Moreover, for other developers to build the extension from the source they sometimes have problems to add Westend manually like asked here: https://github.com/w3f/Grant-Milestone-Delivery/pull/387#issuecomment-1066756970

Hence, We believe adding Westend to the required packages like ss58-registry make stuff more convenient not only for developers but also for community.

Thank you,
Kami

PS: a screenshot of PLUS which illustrates Westend as a supported chain: image

**Comment by bkchr** [comment]
Ty for describing your issue :) I opened a ticket for this: https://github.com/paritytech/ss58-registry/issues/85

**Pull request closed without merging**
