### PR TITLE
Add InvArch

### PR DESCRIPTION
**Pull request by arrudagates**

### CODE REVIEW

**Comment by arrudagates** [comment]
@BenWhiteJam We will be launching our testnet on Rococo on the 25th, any update on this?

**Comment by bkchr** [comment]
Tests nets don't get their own prefix.

**Comment by arrudagates** [comment]
We do plan to use the same prefix aa the one we would be reserving for
mainnet, is that also not possible?

-- 
Gabriel Facco de Arruda
+55 (51) 99826-0101
***@***.***

**Comment by bkchr** [comment]
It is possible, but from a user perspective this doesn't make that much sense. The prefix should ensure that you not by accident send something to a different network, which you here would easily open a door for. Because someone could maybe copy an address of the test net, which may not exists on the real network or the private key is known or something. Just use the generic prefix `42` as every test net.

**Comment by arrudagates** [comment]
@bkchr I updated the PR to reflect our Tinker Kusama parachain, which will be going for a slot auction and crowdloan in the near future

**Review by BenWhiteJam — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
