### PR TITLE
add Autonomys network

### PR DESCRIPTION
**Pull request by dariolina**
Added Autonomys network (https://www.autonomys.xyz/) and bumped minor version to "1.51.0"

### CODE REVIEW

**Comment by dariolina** [comment]
Hi @bkchr @SBalaguer
I understand that Parity is looking to revamp the registry, however, we are looking to launch Autonomys mainnet within a few weeks ([blog](https://medium.com/subspace-network/the-phases-of-mainnet-3a08d7aa7178)) so would greatly appreciate a review and release of this crate.
Thank you for understanding!

**Comment by SBalaguer** [comment]
@dariolina all looks good to me, however I do have a question: Isn't Autonomys a rebranding of Subpsace, and so you wouldn't need a new SS58 but rather a modification of the previous one? Or are you keeping both blockchains running simultaneously?

Also as you said, there's a discussion going on in the ecosystem regarding ss58, so this registry might be shut down in the future.

**Comment by dariolina** [comment]
@SBalaguer thanks for a speedy response!
Indeed, it is a rebranding of Subspace, but adding a new entry kind of felt less invasive. Happy to modify.

**Comment by SBalaguer** [comment]
I see! Then if it's a rebranding and you're using the same chain as you have today, you can go ahead and modify the existing entry. If subspace won't exist as it used to anymore, this is probably the best.

**Review by bkchr — APPROVED** [review]

**Comment by dariolina** [comment]
Thanks for the review @bkchr ! Is there anything I need to do to get this merged and released to crates?

**Comment by bkchr** [comment]
@dariolina please merge master to make this pr mergable.

**Pull request merged**
