### PR TITLE
Register logion's prefix

### PR DESCRIPTION
**Pull request by gdethier**

### CODE REVIEW

**Comment by gdethier** [comment]
Build failure seems related to a CI issue: `error: 'cargo-clippy' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'`.

**Comment by bkchr** [comment]
> Build failure seems related to a CI issue: `error: 'cargo-clippy' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'`.

Ty for the report, it will be fixed!

**Comment by altaua** [comment]
> Build failure seems related to a CI issue: `error: 'cargo-clippy' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'`.

Fixed in #173, please rebase :)

**Comment by gdethier** [comment]
Done, thanks!

**Comment by DanielCake-Baly** [comment]
Hey @gdethier, Could you please contact me on [Element](https://matrix.to/#/@daniel_cb:parity.io)? Thanks in advance!

**Review by DanielCake-Baly — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
