### PR TITLE
Fix Efinity account type

### PR DESCRIPTION
**Pull request by leonardocustodio**

### CODE REVIEW

**Comment by DanielCake-Baly** [comment]
Hey @leonardocustodio! 
Rocfinity is a testnet, isn't it? If yes, it should use the generic prefix 42.

**Comment by leonardocustodio** [comment]
Yes, it is the testnet of Efinity, and a parachain of Rococo. We've been using the prefix 195 for quite a while. There is also other tests net in here with a custom prefix instead of 42. Is that required?

**Comment by bkchr** [comment]
Yeah, no prefixes for test nets. All test nets should use the 42 prefix.

**Comment by leonardocustodio** [comment]
Ok, I'm removing rocfinity from the PR and only leaving the accounttype change for efinity. Thanks.

**Review by bkchr — APPROVED** [review]

**Pull request merged**
