### PR TITLE
feat: Adds VOW chain prefix

### PR DESCRIPTION
**Pull request by thadouk**

### CODE REVIEW

**Review by ivan-cholakov — APPROVED** [review]

**Comment by thadouk** [comment]
@bkchr could you review when you have some time?
Thanks :raised_hands:

**Comment by bkchr** [comment]
CC @SBalaguer

**Comment by thadouk** [comment]
hey @bkchr @SBalaguer
We are getting closer to the launch day and need to have this merged in order to use the prefix on the chain. Is it possible to get this reviewed and hopefully merged?
Thanks in advance for your help.

**Comment by SBalaguer** [comment]
@bkchr looks good to me for merging.

**Review by SBalaguer — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
