### PR TITLE
Add SORA Kusama Parachain

### PR DESCRIPTION
**Pull request by KalitaAlexey**

### CODE REVIEW

**Comment by takemiyamakoto** [comment]
This is in preparation for setting up a new network for our kusama parachain, as explained here: https://medium.com/sora-xor/the-sora-network-kusama-parachain-auction-5a6fe3a5f35f

**Comment by KalitaAlexey** [comment]
Is there anything required from us?

**Comment by takemiyamakoto** [comment]
We are waiting on this before starting our Kusama crowdloan. There are around 20,000 people waiting, so is there any estimate on when it can be merged?

**Comment by bkchr** [comment]
> Is there anything required from us?

You need to get into contact with @BenWhiteJam

**Comment by takemiyamakoto** [comment]
> > Is there anything required from us?
> 
> You need to get into contact with @BenWhiteJam

Thanks for the reply. Can he contact us?
t@soramitsu.co.jp

**Comment by BenWhiteJam** [comment]
@bkchr: Sora guys are saying they are getting this error because of the missing prefix:

`Calling any extrinsic when prefix is 420, I get RPC-CORE: accountNextIndex(accountId: AccountId): Index:: -32602: Invalid params: UnknownVersion.`

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/pull/10541 created this to explain the error better.

**Review by BenWhiteJam — APPROVED** [review]
@bkchr happy to approve but don't we need to bump the version as well?

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> @bkchr happy to approve but don't we need to bump the version as well?

Is fine, this will then just be released the next time we bump the version.

**Pull request merged**
