### PR TITLE
Add Enjin & Matrixchain

### PR DESCRIPTION
**Pull request by leonardocustodio**
We are moving from Efinity to Enjin Matrixchain, this PR updates it and adds Enjin Blockchain. We've already changed our slip044 as well: https://github.com/satoshilabs/slips/pull/1598

### CODE REVIEW

**Comment by SBalaguer** [comment]
Given the intended nature of the Enjin Blockchain ecosystem's growth, I believe that the best course of action is to rather fork this registry and keep one that fully suits your needs, current and future.

I think this stands too for PolkadotJS, so I'll be commenting that on [here](https://github.com/polkadot-js/apps/pull/9870) too.

**Comment by leonardocustodio** [comment]
Hello @SBalaguer, Would you mind to explain what is the "intended nature of the Enjin Blockchain ecosystem growth"? And why is it different from the various standalone chains that are also here and are not parachains of polkadot? Regards

**Comment by SBalaguer** [comment]
My point is that with the objective of the Enjin Blockchain and the consequent Matrixchain [explained on it's whitepaper](https://enjin.io/whitepaper), the best course of action is to fork this registry and keep a list of the top-level blockchain with all the subsequent connected chains (like Enjin Matrixchain and whatever others might come in the future). This predicted growth future is what makes the essence of Enjin Blockchain and Enjin Matrixchain different than any other solochain, and that it's why forking will be most probably best to suit your needs, current and future.

**Comment by leonardocustodio** [comment]
I understand your point but I don't really agree with it. This is a registry of SS58 prefixes it basically maps any substrate chain that uses SS58 as a standard to the prefix that it uses to make the lives of other developers easier. There is no point in making a fork of a registry it would do the exact opposite, making the life of developers harder.
Also, it doesn't say in the docs, nor the repo, nor anywhere. That relaychains and parachains of other relaychains cannot be registered here. I mean like I said a "ss58registry" not a "polkadot relaychain registry" as we can see for the lots of standalone chains that we have here. I would like your reconsideration, otherwise, I would like to know if that's an official Parity response and not just your personal opinion.

**Comment by leonardocustodio** [comment]
As we don't get any answer, @gavofyork, can you confirm to us that's the official parity decision? To not operate a ss58 registry without bias, as people do with slip044 is operated with an independent party?

**Comment by bkchr** [comment]
Hey, I would be open to approve and merge your pull request. I would just have one requirement before doing this, please open up any code that was forked from us. The node side is GPL3 licensed and requires to open up any changes any way. We are believing in open source and this is also better for the Substrate ecosystem. In the future you should then also help us to identify actual builders in your ecosystem to prevent that the registry is spammed.

**Comment by leonardocustodio** [comment]
Hello @bkchr, thank you for your response.
If you don't mind I would like to make a comment about the following point as I'm not sure you are aware of our work.
> We are believing in open source and this is also better for the Substrate ecosystem.

Enjin is very committed to the open-source community and we also believe we can do great things together. Every single project that I work on forked or not is open-source and was done in a way that is generic enough for any substrate chain to integrate with it. Here is a list of a few of them:

- https://github.com/enjin/wallet-daemon
- https://github.com/enjin/platform
- https://github.com/enjin/platform-core
- https://github.com/enjin/platform-csharp-sdk
- https://github.com/enjin/ledger-enjin
- https://github.com/enjin/platform-ui
- https://github.com/enjin/platform-beam
- https://github.com/enjin/ledger-matrixchain
- https://github.com/enjin/platform-marketplace
- https://github.com/enjin/platform-fuel-tanks
- https://github.com/enjin/platform-cpp-sdk
- https://github.com/enjin/php-blockchain-tools

**Comment by bkchr** [comment]
@leonardocustodio where can I find your actual Substrate chain?

**Pull request closed without merging**
