### PR TITLE
add DICO chain prefix

### PR DESCRIPTION
**Pull request by cj1afs**
add [dico-chain](https://github.com/DICO-TEAM/dico-chain) chain prefix

### CODE REVIEW

**Comment by cj1afs** [comment]
@bkchr hello, our testnet needs this account prefix.

**Comment by bkchr** [comment]
Please get in contact with @BenWhiteJam.

However, test nets don't need their own ss58 prefix.

**Comment by cj1afs** [comment]
> Please get in contact with @BenWhiteJam.
> 
> However, test nets don't need their own ss58 prefix.

hi, this is not only for  test nets, we are preparing for ksm net and dot net.

**Comment by DICO-TEAM** [comment]
hello @bkchr , It's been 17 days ago, can you help us handle it?

image

**Comment by DICO-TEAM** [comment]
Add KICO(for ksm net), DICO(for dot net) to ss58 registry

**Comment by BenWhiteJam** [comment]
Could you provide a testnet endpoint?

**Comment by DICO-TEAM** [comment]
> Could you provide a testnet endpoint?

yes,  our KICO testnet endpoint: rpc.kico.dico.io

**Comment by DICO-TEAM** [comment]
Hi @BenWhiteJam @bkchr 

We are going to kusama parachain slot within a week or two. Is this prefix merged after the auction?

**Comment by DICO-TEAM** [comment]
our TICO (release) testnet endpoint: rpc.tico.dico.io. It has been running stably for a while

**Review by BenWhiteJam — APPROVED** [review]

**Comment by bkchr** [comment]
@DICO-TEAM please merge master

**Comment by cj1afs** [comment]
> @DICO-TEAM please merge master



> @DICO-TEAM please merge master

Thankyou,

**Comment by cj1afs** [comment]
@bkchr fixed, thankyou

**Review by bkchr — APPROVED** [review]

**Pull request merged**
