### PR TITLE
Add ss58 registry for OAK Network, and its canary network Turing Network.

### PR DESCRIPTION
**Pull request by imstar15**
This is for OAK Network's parachains.

main network: OAK
canary network: Turing

You can find more information here: https://docs.oak.tech/docs/overview/

### CODE REVIEW

**Comment by imstar15** [comment]
Please help review this PR. Thanks!

@bkchr

**Comment by BenWhiteJam** [comment]
@imstar15 would you mind elaborating what do you mean by testnet?

**Comment by irsal** [comment]
> @imstar15 would you mind elaborating what do you mean by testnet?

hi @BenWhiteJam - I work with @imstar15, the Neumann testnet can be found here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fneumann.api.onfinality.io%2Fpublic-ws#/explorer

It's the environment before our canary parachain launches on kusama. We also plan to use the same prefix for our canary network (launching soon). Do you need more information?

**Comment by irsal** [comment]
@BenWhiteJam - anything else we need to provide to get this moving along?

**Review by BenWhiteJam — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by chrisli30** [comment]
> @imstar15 please merge master

Thanks @bkchr ! 😄

**Comment by bkchr** [comment]
bot merge

**Pull request merged**
