### PR TITLE
Add Energy Web X network

### PR DESCRIPTION
**Pull request by renesy**

### CODE REVIEW

**Review by DanielCake-Baly — APPROVED** [review]

**Comment by renesy** [comment]
Added our testnet to the PR

**Comment by DanielCake-Baly** [comment]
> Added our testnet to the PR

Hi @renesy, please note that testnets don't get their own prefix, they can use the standard '42'.

**Comment by renesy** [comment]
> > Added our testnet to the PR
> 
> Hi @renesy, please note that testnets don't get their own prefix, they can use the standard '42'.

I see. Is this a recent change? Because there are testnets with their own prefix already and we'd like to test our tooling with a custom prefix

**Comment by renesy** [comment]
Reverted the last commit and removed testnet registration

**Comment by DanielCake-Baly** [comment]
> I see. Is this a recent change? Because there are testnets with their own prefix already and we'd like to test our tooling with a custom prefix

I'm not sure if this rule exists from day 1, but there were no recent changes on this. 
Also sometimes canary networks are named as testnets but they are not considered as one.

**Comment by renesy** [comment]
> I'm not sure if this rule exists from day 1, but there were no recent changes on this. Also sometimes canary networks are named as testnets but they are not considered as one.

Thanks for the explanation. That's the case for us as well. REX is much more a canary network with the aim to keep it up and test future network upgrades and new application versions in a continuous fashion.

Having said that, could you please merge this PR for EWX @DanielCake-Baly and we'll look into the canary vs. testnet topic on our side?

**Comment by renesy** [comment]
@bkchr Can you please approve and merge this?

**Review by bkchr — APPROVED** [review]

**Pull request merged**
